_BASE_: [
  '../../datasets/mot.yml',
  '../../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/fairmot_dla34.yml',
  '_base_/fairmot_reader_1088x608.yml',
]

weights: output/fairmot_dla34_30e_1088x608/model_final

EvalDataset:
  name: MOTImageFolder
  dataset_dir: dataset/mot
  data_root: MOT17/images/train
  keep_ori_im: False # set True if save visualization images or video, or used in DeepSORT
  data_fields: ['image']
